### ISSUE TITLE
Can't execute eb commands, I'm sure it's just a configuration issue

### ISSUE THREAD

**Issue by siderakis** [sqs/sbt-elasticbeanstalk#2]
I'm able to upload the war to s3, and run the `eb-api-*` commands, however any other eb command fails during `eb-existing-environments`, any tips?

[MyProject] $ eb-config-pull
[error](*:eb-existing-environments) java.util.NoSuchElementException: None.get
[error] Total time: 4 s, completed Jun 17, 2013 1:57:00 PM
[MyProject] $ last
[debug] Running task... Cancelable: false, check cycles: false
java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:274)
    at scala.None$.get(Option.scala:272)
    at com.blendlabsinc.sbtelasticbeanstalk.ElasticBeanstalkCommands$$anonfun$10$$anonfun$15.apply(Commands.scala:187)
    at com.blendlabsinc.sbtelasticbeanstalk.ElasticBeanstalkCommands$$anonfun$10$$anonfun$15.apply(Commands.scala:186)
    at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:315)
    at scala.collection.TraversableLike$$anonfun$groupBy$1.apply(TraversableLike.scala:314)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:76)
    at scala.collection.TraversableLike$class.groupBy(TraversableLike.scala:314)
    at scala.collection.immutable.List.groupBy(List.scala:76)
    at com.blendlabsinc.sbtelasticbeanstalk.ElasticBeanstalkCommands$$anonfun$10.apply(Commands.scala:186)
    at com.blendlabsinc.sbtelasticbeanstalk.ElasticBeanstalkCommands$$anonfun$10.apply(Commands.scala:178)
    at sbt.Scoped$$anonfun$hf3$1.apply(Structure.scala:579)
    at sbt.Scoped$$anonfun$hf3$1.apply(Structure.scala:579)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:49)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.Scoped$Reduced$$anonfun$combine$1$$anonfun$apply$12.apply(Structure.scala:311)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:41)
    at sbt.std.Transform$$anon$5.work(System.scala:71)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:238)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
[error](*:eb-existing-environments) java.util.NoSuchElementException: None.get
[error] Total time: 4 s, completed Jun 17, 2013 1:57:00 PM

**Comment by sqs** [comment]
Hmm, can you paste your config or a condensed repro?

**Comment by siderakis** [comment]
Checking out the current branch and using it locally fixed that error.

Thanks for creating this plugin!

**Comment by sqs** [comment]
Glad you got it to work!

**Comment by MaggieLeber** [comment]
I think the problem here is that when an environment is created from a default template, the template name and description get sent down from AWS as null. 

I'm waiting for somebody who's actually trusted with our AWS crap to give me the authority to make a template to get around this. 

Today I'm gradually turning my dark suspicions about EB into a well-founded hatred. :-)

**Comment by MaggieLeber** [comment]
Is there any chance there will be another point release that picks up fixes on trunk since 0.0.6 went to the repo? If not I suppose I'll be learning how to set up my own SBT repo...

**Comment by sqs** [comment]
Yeah, I'll do that. I will need a few days. If you or anyone else is interested in taking over as maintainer, I would be happy to hand over the commit bit and keys.

**Comment by MaggieLeber** [comment]
Thanks... my interest in taking over as maintainer will probably be
influenced by whether we end up deploying our new app in EB or some other
way.

Frankly, I'm lobbying internally against using EB, even though we have a
legacy app that currently runs there...so far nobody's shown me the
technical case for hobbling our work in Play with running under Tomcat; it
just Don't Seem Right.
